//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESIS002
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePedidoMedico
    {
        public int IdDetallePedidoMedico { get; set; }
        public bool PagadoDetallePedidoMedico { get; set; }
        public bool RealizadoDetalleMedico { get; set; }
        public string ResultadosDetalleMedico { get; set; }
    
        public virtual PedidoExamenMedico PedidoExamenMedico { get; set; }
        public virtual ExamenMedico ExamenMedico { get; set; }
    }
}
