//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESIS002
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnostico
    {
        public int IdDiagnostico { get; set; }
        public System.DateTime FechaDiagnostico { get; set; }
        public string SubjetivoDiagnostico { get; set; }
        public string ObjetivoDiagnostico { get; set; }
        public string AnalisisDiagnostico { get; set; }
        public string PlanDiagnostico { get; set; }
        public int DiasReposoDiagnostico { get; set; }
    
        public virtual Paciente Paciente { get; set; }
        public virtual Enfermedad Enfermedad { get; set; }
    }
}
