//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESIS002
{
    using System;
    using System.Collections.Generic;
    
    public partial class Egreso
    {
        public int IdEgreso { get; set; }
        public string ProveedorEgreso { get; set; }
        public string DetalleEgreso { get; set; }
        public double ValorEgreso { get; set; }
        public System.DateTime FechaEgreso { get; set; }
    }
}
