//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESIS002
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingreso
    {
        public int IdIngreso { get; set; }
        public string ProveedorIngreso { get; set; }
        public string DetalleIngreso { get; set; }
        public double ValorIngreso { get; set; }
        public System.DateTime FechaIngreso { get; set; }
    }
}
