//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESIS002
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente : Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paciente()
        {
            this.Diagnostico = new HashSet<Diagnostico>();
            this.SignosVitales = new HashSet<SignosVitales>();
            this.CitaMedica = new HashSet<CitaMedica>();
            this.Procedimiento = new HashSet<Procedimiento>();
        }
    
        public int IdPaciente { get; set; }
        public Nullable<System.DateTime> FechaNacimientoPaciente { get; set; }
        public string EstadoCivilPaciente { get; set; }
        public string GeneroPaciente { get; set; }
        public string TipoSangrePaciente { get; set; }
        public string AlergiasPaciente { get; set; }
        public int HistoriaClinicaPaciente { get; set; }
    
        public virtual ContactoEmergencia ContactoEmergencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diagnostico> Diagnostico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SignosVitales> SignosVitales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CitaMedica> CitaMedica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Procedimiento> Procedimiento { get; set; }
        public virtual PedidoExamenMedico PedidoExamenMedico { get; set; }
    }
}
