//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESIS002
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignosVitales
    {
        public int IdSignosVitales { get; set; }
        public System.DateTime FechaSignosVitales { get; set; }
        public int Temperatura { get; set; }
        public decimal Peso { get; set; }
        public string PresionArterial { get; set; }
        public int FrecuenciaCardiaca { get; set; }
        public int FrecuenciaRespiratoria { get; set; }
        public decimal Talla { get; set; }
    
        public virtual Paciente Paciente { get; set; }
    }
}
