//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESIS002
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VacariModeloContainer : DbContext
    {
        public VacariModeloContainer()
            : base("name=VacariModeloContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ContactoEmergencia> ContactoEmergenciaSet { get; set; }
        public virtual DbSet<Diagnostico> DiagnosticoSet { get; set; }
        public virtual DbSet<Enfermedad> EnfermedadSet { get; set; }
        public virtual DbSet<SignosVitales> SignosVitalesSet { get; set; }
        public virtual DbSet<CitaMedica> CitaMedicaSet { get; set; }
        public virtual DbSet<TipoCitaMedica> TipoCitaMedicaSet { get; set; }
        public virtual DbSet<Procedimiento> ProcedimientoSet { get; set; }
        public virtual DbSet<Factura> FacturaSet { get; set; }
        public virtual DbSet<DetalleFactura> DetalleFacturaSet { get; set; }
        public virtual DbSet<Producto> ProductoSet { get; set; }
        public virtual DbSet<PedidoExamenMedico> PedidoExamenMedicoSet { get; set; }
        public virtual DbSet<DetallePedidoMedico> DetallePedidoMedicoSet { get; set; }
        public virtual DbSet<ExamenMedico> ExamenMedicoSet { get; set; }
        public virtual DbSet<Persona> PersonaSet { get; set; }
        public virtual DbSet<Ingreso> IngresoSet { get; set; }
        public virtual DbSet<Egreso> EgresoSet { get; set; }
        public virtual DbSet<PagoEmpleado> PagoEmpleadoSet { get; set; }
        public virtual DbSet<TipoProcedimiento> TipoProcedimientoSet { get; set; }
    }
}
